services:
  - type: web
    name: lieblingsfilme-backend
    env: node
    root: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: "mongodb+srv://mikegithub_db_user:5jwR3ZGTi8aEHGwG@cluster0.6ddhr0i.mongodb.net/"
    autoDeploy: true
